### PR TITLE
Coming movies

### PR DESCRIPTION
**Pull request by MickeMarten**
Added coming component movies to frontpage.
Made "book" button a nextjs-Link with href: /_id
I'm prioritizing to do small merges instead of big merges.
Maybye making the movie-cards smaller, let me know when you try on a normal screen. My screen is very big and curved with enlarged ui. (Bad eyesight).
I merged my local branch with main in editor. That's why there's so much changes in the code.

Fixed footer-text color and hover effect.
Made footer responsive.
Skärmklipp

### CODE REVIEW

**Review by ConnyPettersson — APPROVED** [review]
Looks great!

**Review by ConnyPettersson — APPROVED** [review]
The book link works well. I tried all the buttons :)

**Review by oskber — APPROVED** [review]
Looks great!

**Comment by ANschoolacc** [comment]
Also noticed the carousel cuts of some of the movies to the left. Otherwise it looks good, i copied alot of the styling for my card "Alla filmer" ;)

**Pull request merged**
