### PR TITLE
Search

### PR DESCRIPTION
**Pull request by MickeMarten**
Added Input-component.
Added searchparams to query the url with user input.
Linked the query to MongoDB to get movies with user input.
Added debounce so we dont overload the database with requests on every keystroke.
Added conditionals with mongoose on the fetchMoviesNow function.
Modal shows 4 movies then the overflow-y-scroll kicks in.
Mobliefirst of course.
Skärmklipp

### CODE REVIEW

**Comment by AntonisTerzo** [comment]
Hello Micke, today i tested the search function and it works really good but i think there is a small problem with it. So lets say i try to search "The lord of the rings" and i type "the" in the search bar i get results from movies that don't have a "the" in their title, for example i got "king kong" as first choice. I think this has to do with the code in "kino-nextjs/app/lib/data.ts line 19" you are doing a query for the description of the movie? so we get results from all the movies that have a "the" in their description. (or maybe i'm completely wrong and i should go to sleep :P) Maybe we should change it to only make queries to the title and the genre of the films. :D 
Capture

**Comment by MickeMarten** [comment]
@AntonisTerzo thanks for pointing it out. You are right, it's fixed now!

**Review by oskber — APPROVED** [review]
Nice, tested and it seems to work!

**Review by AntonisTerzo — APPROVED** [review]
Great job Micke 💪💪

**Pull request merged**
